### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "josbertjg@gmail.com",
  "password": "28150010"
}

### Refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json
Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmOTU1Y2E4LTEzZTgtMTFmMC1hZjE4LTNjN2MzZjgwNmQxOCIsInJvbGUiOiJDQVRFUVVJU1RBIiwiaWF0IjoxNzQ0MDU1MTE5LCJleHAiOjE3NDUzNTExMTl9.RT2ekt7JUg3GzU1qqsZEIPfMtbsmJSOS9Nfgd5vbOzY

{
  "email": "josbertjg@gmail.com",
  "password": "29026225"
}

### Create un confirmando
POST http://localhost:3000/auth/confirmando
Content-Type: application/json

{
  "nombre": "Josbert",
  "apellido": "Guedez",
  "email": "josbertmora@gmail.com",
  "phone": "04145598216",
  "born_date": "2001-10-12",
  "id_parroquia": 40,
  "cedula": "V435434698",
  "primera_comunion": true
}

### Create un catequista
POST http://localhost:3000/auth/catequista
Content-Type: application/json

{
  "nombre": "Josbert",
  "apellido": "Guedez",
  "email": "josbert@gmail.com",
  "phone": "04145598216",
  "born_date": "2001-10-12",
  "id_parroquia": 40,
  "cedula": "V29624809"
}