### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3YmEwMTM1LTBiZGUtMTFmMC05MGZmLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJDQVRFUVVJU1RBIiwiaWF0IjoxNzQzNjQxNTcxLCJleHAiOjE3NDM2NDUxNzF9.IF37pGYPZehyQOJs1nC7Cy8WMSxRJr7newAX2CZS5N0

{
  "email": "josbertjg@gmail.com",
  "password": "29026225"
}

### Create un confirmando
POST http://localhost:3000/auth/confirmando
Content-Type: application/json

{
  "nombre": "Josbert",
  "apellido": "Guedez",
  "email": "josbertconfirmando@gmail.com",
  "phone": "04145598216",
  "born_date": "2001-10-12",
  "id_parroquia": 40,
  "cedula": "V281500",
  "primera_comunion": true
}

### Create un catequista
POST http://localhost:3000/auth/catequista
Content-Type: application/json

{
  "nombre": "Josbert",
  "apellido": "Guedez",
  "email": "josbertcatequista@gmail.com",
  "phone": "04145598216",
  "born_date": "2001-10-12",
  "id_parroquia": 40,
  "cedula": "V29624809"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3YmEwMTM1LTBiZGUtMTFmMC05MGZmLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJDQVRFUVVJU1RBIiwiaWF0IjoxNzQzNjQxNTcxLCJleHAiOjE3NDM2NDUxNzF9.IF37pGYPZehyQOJs1nC7Cy8WMSxRJr7newAX2CZS5N0