### Get todas las catequista
GET http://localhost:3000/catequista

### Get una catequista por id
GET http://localhost:3000/catequista/f9599097-0bdf-11f0-90ff-3c7c3f806d18

### Activar un catequista
POST http://localhost:3000/catequista/activate/3537658b-8a81-435d-b76e-9c57cfdb9bbe