### Get todas las catequista
GET http://localhost:3000/catequista

### Get una catequista por id
GET http://localhost:3000/catequista/f9599097-0bdf-11f0-90ff-3c7c3f806d18

### Activar un catequista
POST http://localhost:3000/catequista/activate/69487e1a-10f8-11f0-9331-3c7c3f806d18