### Get todas las confirmandos
GET http://localhost:3000/confirmando
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY1MTg2NywiZXhwIjoxNzQ0NjU1NDY3fQ.al5QGst3nUKg8QV-8K6ihepfxiMR7ccvtybb5WJI7mo

### Get un confirmando por id
GET http://localhost:3000/confirmando/95f7066f-a2d9-4281-bc84-155803043b39
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY1MTg2NywiZXhwIjoxNzQ0NjU1NDY3fQ.al5QGst3nUKg8QV-8K6ihepfxiMR7ccvtybb5WJI7mo

### Editar a un confirmando
PUT http://localhost:3000/confirmando/95f7066f-a2d9-4281-bc84-155803043b39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY0NjU1MywiZXhwIjoxNzQ0NjUwMTUzfQ.QGl4jTjzRBddQjHA2sQrDuhdyR4AStAKXsYNCAGkYL8

{
  
}

### Inscribir a un confirmando
POST http://localhost:3000/confirmando/inscribir/95f7066f-a2d9-4281-bc84-155803043b39
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY0NjU1MywiZXhwIjoxNzQ0NjUwMTUzfQ.QGl4jTjzRBddQjHA2sQrDuhdyR4AStAKXsYNCAGkYL8