### Get todas los usuarios
GET http://localhost:3000/user

### Get un usuario por id
GET http://localhost:3000/user/17492fad-13a1-434e-9688-09846adc01ce

### User Me
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmOTU1Y2E4LTEzZTgtMTFmMC1hZjE4LTNjN2MzZjgwNmQxOCIsInJvbGUiOiJDQVRFUVVJU1RBIiwiaWF0IjoxNzQ0MDU1MTI3LCJleHAiOjE3NDQwNTg3Mjd9.xSioV2e4VIint-eV5cE-hVkibSJGlu4jNByv-2uQu8A