### Get todas los usuarios
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY1NjMxOSwiZXhwIjoxNzQ0NjU5OTE5fQ.jHfj_HkVgsnArCCyK0j1r182ZPN5ycILJVYJ9c0U5ks

### Get un usuario por id
GET http://localhost:3000/user/17492fad-13a1-434e-9688-09846adc01ce

### User Me
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUzNzVmOWI4LTE3MGYtMTFmMC1hNzNhLTNjN2MzZjgwNmQxOCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NDY1NjMxOSwiZXhwIjoxNzQ0NjU5OTE5fQ.jHfj_HkVgsnArCCyK0j1r182ZPN5ycILJVYJ9c0U5ks