### Get todas los usuarios
GET http://localhost:3000/user

### Get un usuario por id
GET http://localhost:3000/user/17492fad-13a1-434e-9688-09846adc01ce

### User Me
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlYzU3M2E2LTU1NDctNDdlYS04NWE3LWNmMzBlMDk1N2QwZCIsInJvbGUiOiJDT05GSVJNQU5ETyIsImlhdCI6MTc0NDIxNTI0MSwiZXhwIjoxNzQ0MjE4ODQxfQ.L3KMrSPA6G7Fp4sAUqJAzIHOpQMPPej6nU89URA2ukk